config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'

  get 'sessions/create'

  get 'sessions/destroy'

  get 'users/index'

  get 'users/show'

  get 'users/new'

  get 'users/create'

  get 'toppages/index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "toppages#index"
  resources :tasks
  resources :users, only: [:index, :show, :new, :create]
  get "signup", to: "users#new"
  
  get "login", to: "sessions#new"
  post "login", to: "sessions#create"
  delete "logout", to: "sessions#destroy"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :user
  
  validates :content, presence: true, length: {maximum: 255 }
  validates :status, presence: true, length: {maximum: 10 }
  validates :user_id, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
has_many :tasks
  
  before_save { self.email.downcase! }
  validates :name, presence: true, length: { maximum: 50 }
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i },
                    uniqueness: { case_sensitive: false }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  
  include SessionsHelper
  private
  
  def require_user_logged_in
    unless logged_in?
      redirect_to login_url
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    email = params[:session][:email].downcase
    password = params[:session][:password]
    
    if login(email, password)
      flash[:success] = "ログインに成功しました"
      redirect_to @user
    else
      flash.now[:danger] = "ログインに失敗しました"
      render "new"
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:success] = "ログアウトしました"
    redirect_to root_url
  end
  
  private
  #Strong parameter
  
  def login(email, password)
    @user = User.find_by(email: email)
    if @user && @user.authenticate(password)
      session[:user_id] = @user.id
      return true
    else
      return false
    end
  end
  
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :require_user_logged_in
  before_action :correct_user, only: [:show, :edit, :update, :delete]
  
  def index
    @tasks = Task.all.page(params[:page])
  end
  
  def create
    @task = current_user.tasks.new(task_params)
    
    if 
      @task.save
      flash[:success] = "新規タスクが正常に登録されました"
      redirect_to @task
    
    else
      flash.now[:danger] = "新規タスク登録に失敗しました"
      render :new
    
    end
  end
  
  def new
    @task = current_user.tasks.new
  end
  
  def edit
    set_task
  end
  
  def show
    set_task
  end
  
  def update
    set_task
    
    if @task.update(task_params)
       flash[:success] = "タスクが正常に更新されました"
       redirect_to @task
      
    else
       flash.now[:danger] = "タスクの更新に失敗しました"
       render :edit
    end
  end
  
  def destroy
    set_task
    
    if @task.destroy
      flash[:success] = "タスクは正常に削除されました"
      redirect_to root_url
    end
  end
  
  private
 
  def set_task
    @task = Task.find(params[:id])
  end
 
  #Strong Parameter
  def task_params
    params.require(:task).permit(:content, :status)
  end
  
  def correct_user
    @task = current_user.tasks.find_by(id: params[:id])
    unless @task
    redirect_to root_url
    end
  end
end

app/controllers/toppages_controller.rb
class ToppagesController < ApplicationController
  def index
    if logged_in?
      @user = current_user
      @tasks = current_user.tasks.page(params[:page])
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_user_logged_in, only: [:index, :show]
  before_action :set_user, only: [:show]
  before_action :correct_user, only: [:show]
  
  def index
    @users = User.all.page(params[:page])
  end

  def show
    @tasks = User.find(params[:id]).tasks.page(params[:page])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    
    if @user.save(user_params)
      flash[:success] = "ユーザを登録しました"
      redirect_to @user
    else
      flash.now[:danger] = "ユーザの登録に失敗しました"
      render :new
    end
  end
  
  private
  #Strong Parameter
  
  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end 
  
  def set_user
    @user = User.find(params[:id])
  end
  
  def correct_user
    redirect_to root_url if current_user != @user
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    @current_user ||=User.find_by(id: session[:user_id])
  end
  
  def logged_in?
    !!current_user
  end
end

app/helpers/toppages_helper.rb
module ToppagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
  def gravatar_url(user, options = { size: 80})
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
  end
end

app/views/layouts/_flash_tasks.html.erb
<% flash.each do |task_type, task| %>
  <div class="alert alert-<%= task_type %>"><%= task %></div>
<% end %>

app/views/layouts/_form.html.erb
<%= form_for(task) do |f| %>

<div class="form-group">
<%= f.label :content, "タスク" %>
<%= f.text_field :content,class: "form-control" %>
</div>

<div class="form-group">
<%= f.label :status, "ステータス" %>
<%= f.text_field :status, class: "form-control" %>
</div>



<%= f.submit "登録" %>
<% end %>

app/views/layouts/_navbar.html.erb
<header>
  <nav class="navbar navbar-inverse navbar-static-top">
    <div class="container">
      <div class="navbar-header">
        
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="/"><span class="glyphicon glyphicon-calendar"></span>Tasklist</a>
      </div>
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav navbar-right">
          <% if logged_in? %>
            <li><%#= link_to "Users", users_path %></li>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><%= current_user.name %><span class="caret"></span></a>
              <ul class="dropdown-menu">
                <li><%= link_to "My profile", user_path(current_user) %></li>
                <li role="separator" class="divider"></li>
                <li><%= link_to "Log out", logout_path, method: :delete %></li>
              </ul>
            </li>
          <% else %>
            <li><%= link_to "Sign up", signup_path %></li>
            <li><%= link_to "Log in", login_path %></li>
          <% end %>
        </ul>
      </div>
    </div>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    
    <title>Tasklist</title>
    <%= csrf_meta_tags %>
    
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    
    
  </head>

  <body>
    <%= render "layouts/navbar" %>
    
    <div class ="container">
    <%= render "layouts/flash_tasks" %>
    <%= yield %>
    </div>
  </body>
</html>

app/views/tasks/_form.html.erb
<%= form_for(task) do |f| %>

  <% if task.errors.any? %>
      <div id="error_explanation">
        <ul>
          <% task.errors.full_messages.each do |task| %>
            <li><%= task %></li>
          <% end %>
        </ul>
      </div>
  <% end %>

<div class="col-sm-offset-2 col-sm-8 col-sm-offset-2 col-lg-offset-3 col-lg-6 col-lg-offset-3">
<div class="form-group">
  <%= f.label :content, "タスク" %>
  <%= f.text_field :content, class: "form-control" %>
</div>


<div class="form-group">
  <%= f.label :status, "ステータス" %>
  <%= f.text_field :status, class: "form-control" %>
</div>

<%= f.submit "登録", class: "btn btn-primary" %>
</div>

<% end %>

app/views/tasks/_tasks.html.erb
  <table class="table table-hover table-striped table-condensed">
    <tr>
      <th>ID</th>
      <th>ユーザ名</th>
      <th>ユーザID</th>
      <th>タスク内容</th>
      <th>ステータス</th>
    </tr>
    <% @tasks.each do |task| %>
    <tr>
      <th><%= link_to task.id, task %></th>
      <th><%= link_to task.user.name, user_path(task.user) %></th>
      <th>ID:<%= task.user_id%></th>
      <th><%= task.content %></th>
      <th><%= task.status %></th>
    </tr>
    <% end %>
  </table>

<%= link_to "新規タスクの登録", new_task_path, class: "btn btn-primary" %>

<%= paginate @tasks %>

app/views/tasks/edit.html.erb
<h1>タスク編集</h1>

<%= render "form", task: @task %>

app/views/tasks/index.html.erb
<h1>タスク一覧</h1>

  <table class="table table-hover table-striped table-condensed">
    <tr>
      <th>ID</th>
      <th>ユーザ名</th>
      <th>ユーザID</th>
      <th>タスク内容</th>
      <th>ステータス</th>
    </tr>
    <% @tasks.each do |task| %>
    <tr>
      <th><%= link_to task.id, task %></th>
      <th><%= link_to task.user.name, user_path(task.user) %></th>
      <th>ID:<%= task.user_id%></th>
      <th><%= task.content %></th>
      <th><%= task.status %></th>
    </tr>
    <% end %>
  </table>

<%= link_to "新規タスクの登録", new_task_path, class: "btn btn-primary" %>

<%= paginate @tasks %>

app/views/tasks/new.html.erb
<h1>新規タスク登録</h1>

<%= render "form", task: @task %>

app/views/tasks/show.html.erb
<h1>id:<%= @task.id %>のタスク詳細表示</h1>

<table class="table table-bordered">
  <tr>
    <th>ID</th>
    <td><%= @task.id %></td>
  </tr>
  
  <tr>
    <th>ユーザ名</th>
    <td><%= @task.user.name %></td>
  </tr>  
  
  <tr>
    <th>ユーザID</th>
    <td><%= @task.user_id %></td>
  </tr>
  
  <tr>
    <th>タスク内容</th>
    <td><%= @task.content %></td>
  </tr>
  <tr>
    <th>ステータス</th>
    <td><%= @task.status %></td>
  </tr>
</table>

<% if current_user == @task.user %>
  <%= link_to "このタスクを更新する", edit_task_path(@task),class: "btn btn-default" %>
  <%= link_to "このタスクを削除する", @task, method: :delete, data: {confirm: "本当に削除して宜しいですか？"},class:"btn btn-danger" %>
<% end %>

app/views/toppages/index.html.erb
<% if logged_in? %>
 <h1>タスク一覧</h1>
 <%= render "tasks/tasks" %>
<% else %>
  <div class="center jumbotron">
    <div class="text-center">
      <h1>Welcome to Tasklist</h1>
      <%= link_to "Sign up now!", signup_path, class: "btn btn-lg btn-primary" %>
    </div>
  </div>
<% end %>

app/views/users/_users.html.erb
<% if users.any? %>
  <ul class="media-list">
    <% users.each do |user| %>
      <li class="media">
        <div class="media-left">
          <img class="media-object img-rounded" src="<%= gravatar_url(user, { size: 50 }) %>" alt="">
        </div>
        <div class="media-body">
          <div>
            <%= user.name %>
          </div>
          <div>
            <p><%= link_to "View profile", user_path(user) %></p>
          </div>
        </div>
      </li>
    <% end %>
  </ul>
<% end %>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/index.html.erb
<%= render "users", users: @users %>

app/views/users/new.html.erb
<div class="text-center">
  <h1>Sign up</h1>
</div>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    
    <%= form_for(@user) do |f| %>
      
      <div class="form-group">
        <%= f.label :name, "Name" %>
        <%= f.text_field :name, class: "form-control" %>
      </div>
      
      <div class="form-group">
        <%= f.label :email, "Email" %>
        <%= f.email_field :email, class: "form-control" %>
      </div>
      
      <div class="form-group">
        <%= f.label :password, "Password" %>
        <%= f.password_field :password, class: "form-control" %>
      </div>
      
      <div class="form-group">
        <%= f.label :password_confirmation, "Confirmation" %>
        <%= f.password_field :password_confirmation, class: "form-control" %>
      </div>
      
      <%= f.submit "Sign up", class: "btn btn-primary btn-block" %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<div class="row">
  <aside class="col-xs-4">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h3 class="panel-title"><%= @user.name %></h3>
      </div>
      <div class="panel-body">
        <img class="media-object img-rounded img-responsive" src="<%= gravatar_url(@user, { size:500 } ) %>" alt="">
      </div>
    </div>
  </aside>
  <div class="col-xs-8">
    <ul class="nav nav-tabs nav-justified">
      <li><a href="#">Task一覧</a></li>
    </ul>
    <%= render "tasks/tasks" %>
  </div>
</div>